version: '3.9'

services:
    mongo:
        image: mongo:5.0
        restart: unless-stopped
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        volumes:
            - ./data/new_driftlon:/data/db
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - 27017:27017
    fetch_games:
        depends_on:
            - "mongo"
        build:
            context: .
            dockerfile: ./Dockerfile.games
        volumes:
            - /var/log/driftlon:/var/log/driftlon
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
    fetch_pros:
        depends_on:
            - "mongo"
        build:
            context: .
            dockerfile: ./Dockerfile.pros
        volumes:
            - /var/log/driftlon:/var/log/driftlon
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
    fetch_casuals:
        depends_on:
            - "mongo"
        build:
            context: .
            dockerfile: ./Dockerfile.casuals
        volumes:
            - /var/log/driftlon:/var/log/driftlon
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
