FROM python:3.7-alpine
RUN apk add --update --no-cache g++ gcc libxslt-dev
COPY fetch_requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./data_fetcher/ /data_fetcher
COPY ./fetch_batch.sh /
COPY ./config.yml /
COPY ./driftlon_utils.py /
ENV PYTHONPATH "${PYTHONPATH}:/"
CMD ["python3", "data_fetcher/fetch.py", "--type", "casuals", "--config", "0"]
# TODO use conda 