FROM python:3.7-alpine
RUN apk add --update --no-cache g++ gcc libxslt-dev
COPY fetch_requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./data_fetcher/ /data_fetcher
COPY ./config.yml /
COPY ./driftlon_utils.py /
ENV PYTHONPATH "${PYTHONPATH}:/"
CMD ["python3", "data_fetcher/mail_warning.py", "/data"]
